
###
GET http://localhost:3001/api/persons
Accept: application/json

###
GET  http://localhost:3001/api/info
Accept: application/json


###
GET http://localhost:3001/api/persons/626c76f47088fcc9be12daf5
Accept: application/json


###
DELETE http://localhost:3001/api/persons/6296976b99dcd23dfe9e248a
Accept: application/json


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Timo",
    "number": "1234556"
}

###
PUT http://localhost:3001/api/persons/626c76f47088fcc9be12daf5
Content-Type: application/json

{
    "name": "Anna",
    "number": "040-1234556"
}
